import { test, expect } from '@playwright/test';
import { loginAsAdmin, gotoAdminTab } from './helpers';
const image = 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="120" height="90"%3E%3Crect width="120" height="90" fill="%238f9986"/%3E%3C/svg%3E';
test('HERO候補を探して並べ替え、公開順を保持して追加できる', async ({page})=>{
 const photos=Array.from({length:24},(_,i)=>({id:i+1,title:`Photo ${i+1}`,filename:`photo-${i+1}.jpg`,url:image,thumbUrl:image,mediumUrl:image,category:i%2?'portrait':'street',description:'',meta:'',width:i%2?200:400,height:300,sortOrder:i,createdAt:`2026-08-${String(i+1).padStart(2,'0')}`,isPublished:true}));
 let ids=[1,2]; let fail=false; const writes:string[]=[];
 await page.route('**/api/photos**',route=>route.fulfill({json:{photos}}));
 await page.route('**/api/admin/hero-photos**',async route=>{
  const req=route.request();
  if(req.method()==='GET')return route.fulfill({json:{heroPhotos:ids.map((photoId,sortOrder)=>({id:photoId,photoId,sortOrder}))}});
  writes.push(req.method());
  if(fail)return route.fulfill({status:500,json:{error:'test failure'}});
  if(req.method()==='POST')ids.push(req.postDataJSON().photoId);
  if(req.method()==='DELETE')ids=ids.filter(id=>id!==Number(new URL(req.url()).pathname.split('/').pop()));
  await route.fulfill({json:{ok:true}});
 });
 await page.route('**/api/hero-photos**',route=>route.fulfill({json:{heroPhotos:[]}}));
 await loginAsAdmin(page); await gotoAdminTab(page,'hero');
 const candidates=page.locator('[data-hero-candidate]');
 await expect(candidates).toHaveCount(24);
 await expect(candidates.first()).toHaveAttribute('data-hero-candidate','24');
 await page.getByRole('combobox',{name:'候補の並び順'}).selectOption('manual');
 await expect(candidates.first()).toHaveAttribute('data-hero-candidate','1');
 await page.getByRole('searchbox').fill('photo-3.jpg');
 await expect(candidates).toHaveCount(1);
 expect(writes).toEqual([]); expect(ids).toEqual([1,2]);
 await candidates.click();
 await expect(page.locator('[data-hero-slide="3"]')).toBeVisible();
 expect(ids).toEqual([1,2,3]);
 await page.getByRole('searchbox').fill('photo-4.jpg');
 fail=true; await candidates.click();
 await expect(page.getByRole('alert')).toContainText('操作に失敗');
 expect(ids).toEqual([1,2,3]);
 await expect(candidates).toHaveAttribute('aria-pressed','false');
 fail=false; await candidates.click();
 await expect(page.locator('[data-hero-slide="4"]')).toBeVisible();
 await page.getByRole('searchbox').fill('');
 await page.getByRole('button',{name:'絞り込み',exact:true}).click();
 await page.getByRole('combobox',{name:'写真の向き',exact:true}).selectOption('portrait');
 await expect(candidates).toHaveCount(12);
 await page.getByRole('button',{name:'選択済みだけ',exact:true}).click();
 await expect(candidates).toHaveCount(2);
 expect(ids).toEqual([1,2,3,4]);
});
test('HEROの一覧密度と拡大確認、短いスマホでも候補へ戻れる',async({page})=>{
 await loginAsAdmin(page);await gotoAdminTab(page,'hero');
 await expect(page.locator('[data-hero-candidate]').first()).toBeVisible();
 await page.getByRole('combobox',{name:'一覧の密度'}).selectOption('compact');
 await expect(page.locator('.hero-picker-grid')).toHaveAttribute('data-density','compact');
 await page.locator('.hero-candidate footer button').first().click();
 await expect(page.locator('.admin-library-photo-preview')).toBeVisible();
 await page.keyboard.press('Escape');
 await expect(page.locator('.admin-library-photo-preview')).toHaveCount(0);
 await expect(page.locator('.hero-candidate footer button').first()).toBeFocused();
 await page.setViewportSize({width:390,height:667});
 expect((await page.locator('.hero-picker-scroll').boundingBox())!.height).toBeGreaterThan(90);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
 await page.emulateMedia({reducedMotion:'reduce'});
 expect(await page.locator('.hero-candidate-check').first().evaluate(el=>getComputedStyle(el).animationName)).toBe('none');
});
test('写真一覧の取得失敗を空や削除済みと判定せず再試行できる',async({page})=>{
 let fail=true;
 await page.route('**/api/photos**',route=>route.fulfill(fail?{status:500,json:{error:'test'}}:{json:{photos:[]}}));
 await page.route('**/api/admin/hero-photos**',route=>route.fulfill({json:{heroPhotos:[{id:1,photoId:1,sortOrder:0}]}}));
 await loginAsAdmin(page); await gotoAdminTab(page,'hero');
 await expect(page.getByRole('alert')).toContainText('操作に失敗',{timeout:15000});
 await expect(page.getByRole('button',{name:'選択から外す',exact:true})).toHaveCount(0);
 fail=false;await page.getByRole('button',{name:'再読み込み',exact:true}).click();
 await expect(page.locator('.hero-picker')).toBeVisible();
});
