export const SETTINGS_PREVIEW_KEYS = [
  "siteName",
  "siteNameEn",
  "heroSubtitle",
  "heroPhotoUrl",
  "profilePhotoUrl",
  "siteDescription",
  "metaDescriptionHome",
  "metaDescriptionGallery",
  "metaDescriptionAbout",
  "metaDescriptionSeries",
  "metaDescriptionContact",
  "profileName",
  "profileNameKata",
  "profileNameEn",
  "profileBio",
  "profileInstagram",
  "profileTwitter",
  "profileNote",
  "themeBg",
  "themeText",
  "fontJa",
  "fontEn",
  "customFontJaName",
  "customFontJaUrl",
  "customFontEnName",
  "customFontEnUrl",
  "customFontJaCategory",
  "customFontEnCategory",
  "navOpacity",
  "navSize",
  "bodySize",
  "headingSize",
  "sectionLabelSize",
  "sectionLabelOpacity",
  "footerOpacity",
  "footerSize",
  "snsOpacity",
  "heroNameSize",
  "heroNameEnSize",
  "heroNameColor",
  "heroNameEnColor",
  "heroSubSize",
  "heroSubColor",
  "heroNameWeight",
  "bodyWeight",
  "heroNameTracking",
  "heroNameEnTracking",
  "navTracking",
  "sectionLabelTracking",
  "bodyTracking",
  "bodyLeading",
  "sectionLeading",
  "globalFontScale",
  "linkHoverColor",
  "linkUnderline",
  "metaPresetsCamera",
  "metaPresetsLens",
  "footerText",
  "contactIntro",
  "contactNote",
  "contactFlow",
  "contactMessagePlaceholder",
  "contactEmail",
  "formspreeUrl",
  "navLabelTop",
  "navLabelGallery",
  "navLabelAbout",
  "navLabelContact",
  "snsLabelInstagram",
  "snsLabelTwitter",
  "snsLabelNote",
  "worksLabel",
  "viewAllLabel",
  "viewAllCtaLabel",
  "galleryLabel",
  "filterAllLabel",
  "profileLabel",
  "contactLabel",
  "contactSentMessage",
  "contactSendAnother",
  "contactFormName",
  "contactFormEmail",
  "contactFormSubject",
  "contactSubjectOptions",
  "contactFormMessage",
  "contactErrorMessage",
  "contactSendButton",
  "contactSendingButton",
  "accentColor",
  "spacingHeroBottom",
  "spacingSectionGap",
  "spacingPageTop",
  "spacingFooterTop",
  "bgTexture",
  "bgTextureOpacity",
  "photoRevealEffect",
  "navPosition",
  "navHoverEffect",
  "heroMode",
  "heroHeight",
  "heroOverlay",
  "heroDisplayMode",
  "heroTitlePosition",
  "heroScrollEffect",
  "googleSiteVerification",
  "siteUrl",
  "profileStatement",
  "profileGear",
  "footerCtaLabel",
  "galleryGapScale",
  "galleryEmptyRate",
  "gallerySizeVariation",
  "galleryColumns",
  "gallerySizeScale",
  "topWorksColumns",
  "topWorksSizeScale",
  "topWorksGapScale",
  "gallerySeed",
  "galleryLayout",
  "seriesLayout",
  "topWorksLayout",
  "topWorksMode",
  "topWorksIds",
  "seriesGridColumns",
  "seriesGridColumnsMobile",
  "worksDefaultView",
  "smartAlbums",
  "seriesNavEnabled",
  "gallerySortOrder",
  "seriesSortOrder",
  "noteUsername",
  "noteShowCount",
  "noteEnabled",
  "printStoreUrl",
  "printStoreLabel",
  "printEnabled",
  "printDescription",
  "homeCtaEnabled",
  "homeCtaTitle",
  "homeCtaText",
  "homeCtaButton",
  "homeGalleryCount",
  "servicePageConfig",
] as const;

export type SettingsPreviewKey = (typeof SETTINGS_PREVIEW_KEYS)[number];

// The iframe uses a separate React tree/query cache from the admin page. Mirror
// every settings key into that cache so text labels, nav/profile/contact fields,
// and feature toggles preview the same way CSS-variable controls do.
export const JS_PREVIEW_KEYS = SETTINGS_PREVIEW_KEYS;

export function makeSettingsPreviewPayload(
  settings: Record<string, string | undefined>,
): Record<SettingsPreviewKey, string> {
  const payload = {} as Record<SettingsPreviewKey, string>;
  for (const key of SETTINGS_PREVIEW_KEYS) payload[key] = settings[key] ?? "";
  return payload;
}
