export const SETTINGS_PREVIEW_KEYS = [
  "themeBg",
  "themeText",
  "fontJa",
  "fontEn",
  "customFontJaName",
  "customFontJaUrl",
  "customFontEnName",
  "customFontEnUrl",
  "customFontJaCategory",
  "customFontEnCategory",
  "navOpacity",
  "navSize",
  "bodySize",
  "headingSize",
  "sectionLabelSize",
  "sectionLabelOpacity",
  "footerOpacity",
  "footerSize",
  "snsOpacity",
  "heroNameSize",
  "heroNameEnSize",
  "heroNameColor",
  "heroNameEnColor",
  "heroSubSize",
  "heroSubColor",
  "heroNameWeight",
  "bodyWeight",
  "heroNameTracking",
  "heroNameEnTracking",
  "navTracking",
  "sectionLabelTracking",
  "bodyTracking",
  "bodyLeading",
  "sectionLeading",
  "globalFontScale",
  "linkHoverColor",
  "linkUnderline",
  "accentColor",
  "spacingHeroBottom",
  "spacingSectionGap",
  "spacingPageTop",
  "spacingFooterTop",
  "bgTexture",
  "bgTextureOpacity",
  "photoRevealEffect",
  "navPosition",
  "navHoverEffect",
  "heroMode",
  "heroHeight",
  "heroOverlay",
  "heroDisplayMode",
  "heroTitlePosition",
  "heroScrollEffect",
  "galleryGapScale",
  "galleryEmptyRate",
  "gallerySizeVariation",
  "galleryColumns",
  "gallerySizeScale",
  "topWorksColumns",
  "topWorksSizeScale",
  "topWorksGapScale",
  "gallerySeed",
  "galleryLayout",
  "seriesLayout",
  "topWorksLayout",
  "topWorksMode",
  "topWorksIds",
  "seriesGridColumns",
  "seriesGridColumnsMobile",
  "worksDefaultView",
  "seriesNavEnabled",
  "noteUsername",
  "noteShowCount",
  "noteEnabled",
  "printStoreUrl",
  "printStoreLabel",
  "printEnabled",
  "printDescription",
  "homeCtaEnabled",
  "homeCtaTitle",
  "homeCtaText",
  "homeCtaButton",
] as const;

export type SettingsPreviewKey = (typeof SETTINGS_PREVIEW_KEYS)[number];

// These settings drive React render paths instead of CSS variables, so the
// preview iframe must receive them through the TanStack Query cache.
export const JS_PREVIEW_KEYS = [
  "heroMode",
  "heroDisplayMode",
  "heroTitlePosition",
  "heroScrollEffect",
  "navPosition",
  "navHoverEffect",
  "galleryGapScale",
  "galleryEmptyRate",
  "gallerySizeVariation",
  "galleryColumns",
  "gallerySizeScale",
  "topWorksColumns",
  "topWorksSizeScale",
  "topWorksGapScale",
  "gallerySeed",
  "galleryLayout",
  "seriesLayout",
  "topWorksLayout",
  "topWorksMode",
  "topWorksIds",
  "seriesGridColumns",
  "seriesGridColumnsMobile",
  "worksDefaultView",
  "seriesNavEnabled",
  "noteEnabled",
  "noteUsername",
  "noteShowCount",
  "printEnabled",
  "printStoreUrl",
  "printStoreLabel",
  "printDescription",
  "homeCtaEnabled",
  "homeCtaTitle",
  "homeCtaText",
  "homeCtaButton",
] as const satisfies readonly SettingsPreviewKey[];

export function makeSettingsPreviewPayload(settings: Record<string, string | undefined>): Record<SettingsPreviewKey, string> {
  const payload = {} as Record<SettingsPreviewKey, string>;
  for (const key of SETTINGS_PREVIEW_KEYS) payload[key] = settings[key] ?? "";
  return payload;
}
